### PR TITLE
Circle CI 2.0 configs. Serial integrated tests

### PR DESCRIPTION
**Pull request by samuelmattjohnston**
Tests are failing but I'm not sure this is due to the config file or not. Please review your tests.

Future extensions:
- Break out the node dependency building and tests into their own process
- break out the build and container building into separate process
- break out the pushing of containers into a separate process after all builds are green in the pipeline.

### CODE REVIEW

**Comment by AusIV** [comment]
Looks like it's missing the pytest dependency. That should be taken care of by the makefile, so I'll update that.

**Comment by AusIV** [comment]
It wasn't actually a dependency issue, it was something a little more nefarious.

We were executing pip and nosetests directly, as scripts. Normally, the bash interpreter looks at the first line, and it if it starts with

     #!/some/path/to/executable

it will execute `/some/path/to/executable $current_file` 

But it turns out there is a length limit on how long of a shebang will be resolved, and we were exceeding it in the build directory.

To resolve this, I've set the make file to execute the virtual env python directly, and pass the script we want to execute as an argument to the python interpreter, instead of relying on the shebang logic.

**Comment by AusIV** [comment]
It's looking for AWS credentials from IAM roles, which it's not going to find. I think setting the [standard environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) to anything at all should resolve this issue.

**Comment by AusIV** [comment]
There are errors installing packages with dependencies on python async syntax, which I believe was introduced in 3.5. So far I've only tested against 3.6

**Comment by AusIV** [comment]
Also, maybe cut back the environment variables to access key, secret key, and region. I think some of the others might cause problems.

**Comment by AusIV** [comment]
I'm beginning to question the wisdom of going to these lengths to be able to run unittests for a deprecated part of the project.

**Comment by samuelmattjohnston** [comment]
Pretty much right. I am looking at building with different base container images.

**Pull request merged**
